/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.laligacotizacion.vista;

import java.awt.BorderLayout;

/**
 *
 * @author HP
 */
public class VentanaEmpresa extends javax.swing.JPanel {

    /**
     * Creates new form VentanaEmpresa
     */
    
    
    public VentanaEmpresa() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        l_empresas = new javax.swing.JList<>();
        btn_agrEmp = new javax.swing.JButton();
        btn_eliEmpresa = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(650, 550));

        jLabel1.setText("¿Para que empresa es el trabajo?");

        l_empresas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(l_empresas);

        btn_agrEmp.setText("Agregar empresa");
        btn_agrEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agrEmpActionPerformed(evt);
            }
        });

        btn_eliEmpresa.setText("Eliminar empresa");
        btn_eliEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(242, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_agrEmp)
                            .addComponent(btn_eliEmpresa))
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btn_agrEmp)
                        .addGap(30, 30, 30)
                        .addComponent(btn_eliEmpresa)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agrEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agrEmpActionPerformed

        VentanaPrincipal.contenedor.add( VentanaPrincipal.miVentanaAgrEmp);
        VentanaPrincipal.miVentanaAgrEmp.setVisible(true);
        VentanaPrincipal.contenedor.revalidate();
        VentanaPrincipal.contenedor.repaint();
        this.setVisible(false);
        VentanaPrincipal.btn_anterior.setEnabled(true);
        VentanaPrincipal.btn_siguiente.setEnabled(false);
        
    }//GEN-LAST:event_btn_agrEmpActionPerformed

    private void btn_eliEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliEmpresaActionPerformed
        
        VentanaPrincipal.contenedor.add( VentanaPrincipal.miVentanaEliEmp);
        VentanaPrincipal.miVentanaEliEmp.setVisible(true);
        VentanaPrincipal.contenedor.revalidate();
        VentanaPrincipal.contenedor.repaint();
        this.setVisible(false);
        VentanaPrincipal.btn_anterior.setEnabled(true);
        VentanaPrincipal.btn_siguiente.setEnabled(false);
        
    }//GEN-LAST:event_btn_eliEmpresaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agrEmp;
    private javax.swing.JButton btn_eliEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> l_empresas;
    // End of variables declaration//GEN-END:variables
}
