/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.laligacotizacion.vista;

import com.mycompany.laligacotizacion.modelo.Empresa;
import com.mycompany.laligacotizacion.modelo.EmpresaBD;
import java.awt.BorderLayout;
import java.util.ArrayList;

/**
 *
 * @author HP
 */
public class VentanaEmpresa extends javax.swing.JPanel {

    public VentanaEmpresa() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_agrEmp = new javax.swing.JButton();
        btn_eliEmpresa = new javax.swing.JButton();
        jc_empresas = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(650, 550));

        jLabel1.setText("¿Para que empresa es el trabajo?");

        btn_agrEmp.setText("Agregar empresa");
        btn_agrEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agrEmpActionPerformed(evt);
            }
        });

        btn_eliEmpresa.setText("Eliminar empresa");
        btn_eliEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliEmpresaActionPerformed(evt);
            }
        });

        jc_empresas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jc_empresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_empresasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(242, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jc_empresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_agrEmp)
                            .addComponent(btn_eliEmpresa))
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agrEmp)
                    .addComponent(jc_empresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btn_eliEmpresa)
                .addContainerGap(362, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agrEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agrEmpActionPerformed

        VentanaPrincipal.contenedor.add( VentanaPrincipal.miVentanaAgrEmp);
        VentanaPrincipal.miVentanaAgrEmp.setVisible(true);
        VentanaPrincipal.contenedor.revalidate();
        VentanaPrincipal.contenedor.repaint();
        this.setVisible(false);
        VentanaPrincipal.btn_anterior.setEnabled(true);
        VentanaPrincipal.btn_siguiente.setEnabled(false);
        
    }//GEN-LAST:event_btn_agrEmpActionPerformed

    private void btn_eliEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliEmpresaActionPerformed
        
        VentanaPrincipal.contenedor.add( VentanaPrincipal.miVentanaEliEmp);
        VentanaPrincipal.miVentanaEliEmp.setVisible(true);
        VentanaPrincipal.contenedor.revalidate();
        VentanaPrincipal.contenedor.repaint();
        this.setVisible(false);
        VentanaPrincipal.btn_anterior.setEnabled(true);
        VentanaPrincipal.btn_siguiente.setEnabled(false);
        
    }//GEN-LAST:event_btn_eliEmpresaActionPerformed

    private void jc_empresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_empresasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc_empresasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agrEmp;
    private javax.swing.JButton btn_eliEmpresa;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JComboBox<String> jc_empresas;
    // End of variables declaration//GEN-END:variables
}
