/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laligacotizacion.vista;

import com.mycompany.laligacotizacion.modelo.Producto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class VentanaModificar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaModificar
     */
    public VentanaModificar() {
        initComponents();
        Producto miProducto = Producto.listaProductos.get(VentanaPrincipal.miVentanaProductos.row);
        jt_mod_unidades.setText(String.valueOf(miProducto.getUnidades()));
        jt_mod_nombre.setText(String.valueOf(miProducto.getNombre()));
        jt_mod_precioUnitario.setText(String.valueOf(miProducto.getPrecioUnitario()));
        jt_mod_desc.setText(String.valueOf(miProducto.getDescripcion()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jt_mod_unidades = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jt_mod_nombre = new javax.swing.JTextField();
        Unidades = new javax.swing.JLabel();
        jt_mod_precioUnitario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_mod_desc = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Unidades");

        jt_mod_unidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_mod_unidadesActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        Unidades.setText("Precio unitario");

        jt_mod_precioUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_mod_precioUnitarioKeyPressed(evt);
            }
        });

        jLabel4.setText("Descripcion");

        jt_mod_desc.setColumns(20);
        jt_mod_desc.setRows(5);
        jScrollPane1.setViewportView(jt_mod_desc);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(Unidades)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jt_mod_precioUnitario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                .addComponent(jt_mod_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jt_mod_unidades, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jButton1)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jt_mod_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_mod_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Unidades)
                    .addComponent(jt_mod_precioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_mod_unidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_mod_unidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_mod_unidadesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.setVisible(false);
        this.dispose();
        Producto miProducto = new Producto(Integer.parseInt(jt_mod_unidades.getText()), jt_mod_nombre.getText(), jt_mod_desc.getText(), Integer.parseInt(jt_mod_precioUnitario.getText()), true);
        Producto.listaProductos.set(VentanaPrincipal.miVentanaProductos.row, miProducto);
        VentanaPrincipal.miVentanaProductos.t_productos.setValueAt(miProducto.getUnidades(), VentanaPrincipal.miVentanaProductos.row, 0);
        VentanaPrincipal.miVentanaProductos.t_productos.setValueAt(miProducto.getNombre(), VentanaPrincipal.miVentanaProductos.row, 1);
        VentanaPrincipal.miVentanaProductos.t_productos.setValueAt(miProducto.getPrecioUnitario(), VentanaPrincipal.miVentanaProductos.row, 2);
        VentanaPrincipal.miVentanaProductos.t_productos.setValueAt(miProducto.getSubtotal(), VentanaPrincipal.miVentanaProductos.row, 3);
        System.out.println("lista");
        Producto.imprimirLista();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jt_mod_precioUnitarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_mod_precioUnitarioKeyPressed

        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57 || key == ".".charAt(0);
        
        if (!numeros)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_jt_mod_precioUnitarioKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Unidades;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jt_mod_desc;
    private javax.swing.JTextField jt_mod_nombre;
    private javax.swing.JTextField jt_mod_precioUnitario;
    private javax.swing.JTextField jt_mod_unidades;
    // End of variables declaration//GEN-END:variables
}
