/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.laligacotizacion.vista;

/**
 *
 * @author HP
 */
public class VentanaCliente extends javax.swing.JPanel {

    /**
     * Creates new form VentanaIndependiente
     */
    public VentanaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_agrCliente = new javax.swing.JButton();
        btn_eliCliente = new javax.swing.JButton();
        jc_clientes = new javax.swing.JComboBox<>();

        jLabel1.setText("¿Para que cliente es el trabajo?");

        btn_agrCliente.setText("Agregar cliente");
        btn_agrCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agrClienteActionPerformed(evt);
            }
        });

        btn_eliCliente.setText("Eliminar cliente");
        btn_eliCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliClienteActionPerformed(evt);
            }
        });

        jc_clientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jc_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_agrCliente)
                    .addComponent(btn_eliCliente))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48)
                        .addComponent(btn_agrCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jc_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(btn_eliCliente)
                .addContainerGap(318, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agrClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agrClienteActionPerformed
        
        VentanaPrincipal.contenedor.add( VentanaPrincipal.miVentanaAgrClien);
        VentanaPrincipal.miVentanaAgrClien.setVisible(true);
        VentanaPrincipal.contenedor.revalidate();
        VentanaPrincipal.contenedor.repaint();
        this.setVisible(false);
        VentanaPrincipal.btn_anterior.setEnabled(true);
        VentanaPrincipal.btn_siguiente.setEnabled(false);
    }//GEN-LAST:event_btn_agrClienteActionPerformed

    private void btn_eliClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliClienteActionPerformed

        VentanaPrincipal.contenedor.add( VentanaPrincipal.miVentanaEliClien);
        VentanaPrincipal.miVentanaEliClien.setVisible(true);
        VentanaPrincipal.contenedor.revalidate();
        VentanaPrincipal.contenedor.repaint();
        this.setVisible(false);
        VentanaPrincipal.btn_anterior.setEnabled(true);
        VentanaPrincipal.btn_siguiente.setEnabled(false);
        
    }//GEN-LAST:event_btn_eliClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agrCliente;
    private javax.swing.JButton btn_eliCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jc_clientes;
    // End of variables declaration//GEN-END:variables
}
